import React from "react"
import type { NextPage } from "next"
import Head from "next/head"

import LongContent from "@/components/LongContent"

type PageProps = {}

const HomePage: NextPage<PageProps> = ({}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Next page" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline text-center my-4">Video</h1>
        <div className="w-[50%] mx-auto">
          <video width="100%" height="100%" controls>
                            
            <source
              src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
              type="video/mp4"
            />
                        
          </video>
        </div>

        <LongContent />
      </main>
    </>
  )
}

export default HomePage
