import React, { useRef, useEffect } from "react"
import type { NextPage } from "next"
import Head from "next/head"

import LongContent from "@/components/LongContent"
import useIsInViewport from "@/hooks/useIsInViewport"
import styles from "@/styles/home.module.css"

type PageProps = {}

const HomePage: NextPage<PageProps> = ({}) => {
  const containerRef = useRef<HTMLDivElement>(null)
  const isIntersecting = useIsInViewport(containerRef)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Next page" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline text-center my-4">Video</h1>
        <div ref={containerRef}>
          <div
            className={isIntersecting ? "w-[50%] mx-auto" : styles.stickyScreen}
          >
            <video width="100%" height="100%" controls>
                              
              <source
                src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
                type="video/mp4"
              />
                          
            </video>
          </div>
        </div>

        <LongContent />
      </main>
    </>
  )
}

export default HomePage
